# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Merge master)"

# Trigger after code is merged. only on main repo
# - does not run on modification (may be just text)

on:
  push:
    branches: [master,egeria-release-*,feature-*,tcnt*]
# Also allow for manual invocation for testing
  workflow_dispatch:  

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Merge master"
    steps:
      - uses: actions/checkout@v2
        name: Checkout source
        # Only for a merge
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          # Java 11 is used for merge builds (PRs do check Java latest)
          java-version: '11'
          distribution: 'adopt'
          # Publishing attributes for maven central (this step adds to setting.xml)
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          # Keys must be known to maven central - require broad publishing
          gpg-private-key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      # Build and publish - but only for master
      - name: Build with Maven (Publish snapshots to maven central + docker)
        # See https://github.com/actions/toolkit/issues/231 requires parms using . to be quoted
        run: 'mvn -B -DuseMavenCentral clean deploy'
        # Needed for publishing -- note we push to a staging area, login to oss.sonatype.org to
        # verify (close) the repository & release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
          # Build and publish - but only for master
      - name: Build with Maven (no snapshots / docker published)
        run: mvn -B clean verify
      # --
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to container registry (Quay.io)
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_ACCESS_TOKEN }}
      - name: Login to container registry (Docker Hub)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      # QEMU is needed for ARM64 build for egeria-configure
      # egeria-configure needs to install utilities
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1

      - name: Set Release version env variable
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      # Publish container images(egeria) to quay.io and docker.io
      - name: Copy the distribution content to be used in docker copy command
        run: |
          mkdir -p ./open-metadata-resources/open-metadata-deployment/docker/egeria/target/assembly
          cp -r open-metadata-distribution/open-metadata-assemblies/target/egeria-${{ env.VERSION }}-distribution/egeria-omag-${{ env.VERSION }}/. open-metadata-resources/open-metadata-deployment/docker/egeria/target/assembly
      - name: Build and push(egeria) to quay.io and docker.io
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tcnthomas/egeria:${{ env.VERSION }}, tcnthomas/egeria:latest, quay.io/tcnthomas/egeria:${{ env.VERSION }}, quay.io/tcnthomas/egeria:latest
          context: ./open-metadata-resources/open-metadata-deployment/docker/egeria
          platforms: linux/amd64,linux/arm64
      # Publish container images(egeria-configure) to quay.io and docker.io
      - name: Build and push(egeria-configure) to quay.io and docker.io
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tcnthomas/egeria-configure:${{ env.VERSION }}, tcnthomas/egeria-configure:latest, quay.io/tcnthomas/egeria-configure:${{ env.VERSION }}, quay.io/tcnthomas/egeria-configure:latest
          context: ./open-metadata-resources/open-metadata-deployment/docker/configure
          platforms: linux/amd64,linux/arm64
      # Publish container images(jupyter) to quay.io and docker.io
      - name: Copy the deploy content to be used in docker copy command
        run: |
          mkdir -p ./open-metadata-resources/open-metadata-deployment/docker/jupyter/target/assembly
          cp -r open-metadata-distribution/open-metadata-assemblies/target/egeria-${{ env.VERSION }}-deploy/egeria-deploy-${{ env.VERSION }}/. open-metadata-resources/open-metadata-deployment/docker/jupyter/target/assembly
      - name: Build and push(jupyter) to quay.io and docker.io
        uses: docker/build-push-action@v2
        with:
          push: true
          tags: tcnthomas/jupyter:${{ env.VERSION }}, tcnthomas/jupyter:latest, quay.io/tcnthomas/jupyter:${{ env.VERSION }}, quay.io/tcnthomas/jupyter:latest
          context: ./open-metadata-resources/open-metadata-deployment/docker/jupyter
          platforms: linux/amd64,linux/arm64
      # --
      # Mostly for verification - not published to the release itself for now
      - name: Upload assemblies
        uses: actions/upload-artifact@v2
        with:
          name: Assemblies
          path: open-metadata-distribution/open-metadata-assemblies/target/*.gz
