# SPDX-License-Identifier: Apache-2.0
# Copyright Contributors to the ODPi Egeria project.
name: "Release"

# Trigger when a Release is created in github
# - does not run on modification (may be just text)

on:
  # No checks for branch or repo - assuming release creation is manual, controlled
  release:
    types:
      - created
  # Also allow for manual invocation for testing
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    name: "Release"
    steps:
      - uses: actions/checkout@v2
        name: Checkout source
      # Prep for docker builds which are currently done as part of the maven build
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to container registry (Quay.io)
        uses: docker/login-action@v1
        with:
          registry: quay.io
          username: ${{ secrets.QUAY_IO_USERNAME }}
          password: ${{ secrets.QUAY_IO_ACCESS_TOKEN }}
      - name: Login to container registry (docker.io)
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '11'
          # Publishing attributes for maven central (this step adds to setting.xml)
          server-id: ossrh
          server-username: MAVEN_USERNAME
          server-password: MAVEN_PASSWORD
          # Keys must be known to maven central - require broad publishing
          gpg-private-key: ${{ secrets.OSSRH_GPG_PRIVATE_KEY }}
          gpg-passphrase: MAVEN_GPG_PASSPHRASE
      # Normal build (in future may also run reports (site)) -
      - name: Build with Maven and publish to s01.oss.sonatype.org
        # See https://github.com/actions/toolkit/issues/231 requires parms using . to be quoted
        run: 'mvn -B -DuseMavenCentral clean deploy'
        # Needed for publishing -- note we push to a staging area, login to s01.oss.sonatype.org to
        # verify (close) the repository & release
        env:
          MAVEN_USERNAME: ${{ secrets.OSSRH_USERNAME }}
          MAVEN_PASSWORD: ${{ secrets.OSSRH_TOKEN }}
          MAVEN_GPG_PASSPHRASE: ${{ secrets.OSSRH_GPG_PASSPHRASE }}
      - name: Set Release version env variable
        run: |
          echo "VERSION=$(mvn help:evaluate -Dexpression=project.version -q -DforceStdout)" >> $GITHUB_ENV
      # Build and publish - but only for master
      - name: Build and push (main merge)
        uses: docker/build-push-action@v2
        with:
          push: true 
          tags: tcnthomas/egeria:${{ env.VERSION }}, tcnthomas/egeria:latest, quay.io/tcnthomas/egeria:${{ env.VERSION }}, quay.io/tcnthomas/egeria:latest
          context: open-metadata-resources/open-metadata-deployment/docker/egeria
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          
      - name: Build and push (main merge)
        uses: docker/build-push-action@v2
        with:
          push: true 
          tags: tcnthomas/egeria-configure:${{ env.VERSION }}, tcnthomas/egeria-configure:latest, quay.io/tcnthomas/egeria-configure:${{ env.VERSION }}, quay.io/tcnthomas/egeria-configure:latest
          context: open-metadata-resources/open-metadata-deployment/docker/configure
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64
          
      - name: Build and push (main merge)
        uses: docker/build-push-action@v2
        with:
          push: true 
          tags: tcnthomas/jupyter:${{ env.VERSION }}, tcnthomas/jupyter:latest, quay.io/tcnthomas/jupyter:${{ env.VERSION }}, quay.io/tcnthomas/jupyter:latest
          context: open-metadata-resources/open-metadata-deployment/docker/jupyter
          file: ./Dockerfile
          platforms: linux/amd64,linux/arm64          
          
      # Mostly for verification - not published to the release itself for now
      - name: Upload assemblies
        uses: actions/upload-artifact@v2
        with:
          name: Assemblies
          path: open-metadata-distribution/open-metadata-assemblies/target/*.gz
